version: '3.7'
services:
  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/app/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  
  nginx:
    build: ./nginx 
    ports:
      - 80:80 
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE

volumes:
   postgres_data:
